#!/bin/sh

export PROGSDIR=$HOME/Calculix
export HOME_BUILD=$PWD

mkdir -p $PROGSDIR/lib

# Install ARPACK to support CalculiX
echo 'Building ARPACK'
#wget -c --tries=1000000 http://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz
#wget -c --tries=1000000 http://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz
tar xzf arpack96.tar.gz
tar xzf patch.tar.gz
cd ARPACK
patch ARmake.inc ../ARPACK_ARmake.inc.patch
patch UTIL/second.f ../ARPACK_second.f.patch
make lib > ../ARPACK_make.txt 2> ../ARPACK_error.txt
cp libarpack_linux.a $PROGSDIR/lib
cd ..
rm ARPACK -rf
#rm arpack96.tar.gz
#rm patch.tar.gz

