#!/bin/sh

# You must run this in ~/build_calculix (hard coded in the ARPACK patch)
# You will need gcc-fortran, cpio, freeglut, glu

echo "==========Calculix Build==========="
echo "==========Calculix 2.11============"
echo "==================================="
echo "+Download PDF and other documents?\n+(yes/no)"
read download_documents
echo "+Remove all download file after compile?\n+(yes/no)"
read remove_download_file

export PROGSDIR=$HOME/calculix
export PATH=$PROGSDIR/bin:$PATH
export LD_LIBRARY_PATH=$PROGSDIR/lib:$LD_LIBRARY_PATH
export INCLUDE=$PROGSDIR/include:$INCLUDE
export LDFLAGS="-L$PROGSDIR/lib"
export CPPFLAGS="-I$PROGSDIR/include"
export MY_LIB=$PROGSDIR/lib
export MY_INCLUDE=$PROGSDIR/include
export HOME_BUILD=$PWD

mkdir -p $PROGSDIR
mkdir -p $PROGSDIR/bin
mkdir -p $PROGSDIR/lib
mkdir -p $PROGSDIR/doc
mkdir -p $PROGSDIR/include

# functions
# if file exist then just use it, otherwise download it first.
file_download(){
    if [ -f $1 ]; then
        echo $1 "file exist"
    else
        wget -c --tries=1000000 $2
    fi
}
 
# Spooles as solver for CCX
file_download "spooles.2.2.tgz" http://www.netlib.org/linalg/spooles/spooles.2.2.tgz
mkdir SPOOLES.2.2
cp spooles.2.2.tgz SPOOLES.2.2
cd SPOOLES.2.2
tar xzf spooles.2.2.tgz
patch ./Tree/src/makeGlobalLib ../SPOOLES_makeGlobalLib.patch # Fix drawTree
patch Make.inc ../SPOOLES_Make.inc.patch # Fix c compiler location
make lib > ../spooles_make.txt 2> ../spooles_error.txt
cp spooles.a $PROGSDIR/lib
mkdir $PROGSDIR/include/spooles
find . -name '*.h' | cpio -updm $PROGSDIR/include/spooles
cd MT/src
make > ../../../spoolesMT_make.txt 2> ../../../spoolesMT_error.txt
cp spoolesMT.a $PROGSDIR/lib
cd ..
mkdir $PROGSDIR/include/spooles/MT
cp spoolesMT.h $PROGSDIR/include/spooles/MT
cd ../..
if [ $remove_download_file = "yes" ]; then
    rm SPOOLES.2.2 -Rf
    rm spooles.2.2.tgz
fi


# Install ARPACK to support CalculiX
echo 'Building ARPACK'
file_download "arpack96.tar.gz" http://www.caam.rice.edu/software/ARPACK/SRC/arpack96.tar.gz
file_download "patch.tar.gz" http://www.caam.rice.edu/software/ARPACK/SRC/patch.tar.gz
tar xzf arpack96.tar.gz
tar xzf patch.tar.gz
cd ARPACK
patch ARmake.inc ../ARPACK_ARmake.inc.patch
patch UTIL/second.f ../ARPACK_second.f.patch
make lib > ../ARPACK_make.txt 2> ../ARPACK_error.txt
cp libarpack_linux.a $PROGSDIR/lib
cd ..
if [ $remove_download_file = "yes" ]; then
    rm ARPACK -rf
    rm arpack96.tar.gz
    rm patch.tar.gz
fi

# CGX from CalculiX
echo 'Installing CGX'
file_download "cgx_2.11.all.tar.bz2" http://www.dhondt.de/cgx_2.11.all.tar.bz2
tar xjf cgx_2.11.all.tar.bz2
cd CalculiX/cgx_2.11/src
make > ../../../cgx_make.txt 2> ../../../cgx_error.txt
cp cgx $PROGSDIR/bin
cd ../../..
if [ $download_documents = "yes" ]; then
    file_download "cgx_2.11.pdf" http://www.dhondt.de/cgx_2.11.pdf
    cp cgx_2.11.pdf $PROGSDIR/doc/
    if [ $remove_download_file = "yes" ]; then
        rm cgx_2.11.pdf
    fi
fi
if [ $remove_download_file = "yes" ]; then
    rm CalculiX -Rf
    rm cgx_2.11.all.tar.bz2
fi

# CCX 2.11 with pardiso and spooles
echo 'Installing CCX 2.11'
file_download "ccx_2.11.src.tar.bz2" http://www.dhondt.de/ccx_2.11.src.tar.bz2
tar xjf ccx_2.11.src.tar.bz2
cd CalculiX/ccx_2.11
cd src
cp ../../../ccx_Makefile Makefile
make > ../../../ccx_make.txt 2> ../../../ccx_error.txt
cp ccx_2.11 $PROGSDIR/bin
cp LOGBOOK $PROGSDIR/doc
cd ../../..
if [ $download_documents = "yes" ]; then
    file_download "ccx_2.11.pdf" http://www.dhondt.de/ccx_2.11.pdf
    cp ccx_2.11.pdf $PROGSDIR/doc
    if [ $remove_download_file = "yes" ]; then
        rm ccx_2.11.pdf
    fi
fi
if [ $remove_download_file = "yes" ]; then
    rm CalculiX -Rf
    rm ccx_2.11.src.tar.bz2
fi
